### ISSUE TITLE
새 문제들 (C#기준)

### ISSUE THREAD

**Issue by csnewcs** [PMHStudio/DiscordCodeQuizBot#1]
1. int는 32비트 정수형 변수 타입이다 (0)
2. 메서드를 선언할 땐 
   <변수 타입> <이름>()가 없으면 오류가 생긴다 (0)
3. .Net Framework는 MacOS나 Linux에서도 돌아간다 (X) -> .Net Core은 돌아가지만 .Net Framework는 돌아가지 않는다
4. 메서드에는 무조건 중괄호가 있어야한다 (X) -> 문장이 하나일 경우 =>만 해도 된다

**Comment by pmh-only** [comment]
더 자세한 풀이가 필요하며, 이슈 하나당 한문제만 기술해 주십시오
자세한 사항은 [여기](https://github.com/PMHStudio/DiscordCodeQuizBot/issues/new/choose)를 참고하세요
