### ISSUE TITLE
문제 추가!

### ISSUE THREAD

**Issue by csnewcs** [PMHStudio/DiscordCodeQuizBot#2]
(꼭, 이슈 하나당 하나의 문제만 적어주세요!)

## 문제의 언어
ex) Python 3.6
      C# (.Net Framework 4.7.2)

## 문제 (OX로 문제를 풀수있어야 합니다)
(~에서는 ~해서 ~한다.)
조건문 if에는 무조건 중괄호가 있어야 한다
## 답
X

## 풀이
( 자세하게 해줘요! )
기본적으로는

if (조건식)
{실행 문장}

이지만 실행되는 문장이 하나일 경우

if (조건식) 실행 문장

으로 중괄호를 빼는것이 가능하다

**Comment by pmh-only** [comment]
@hj666c2 
문제 No.6으로 반영하였습니다.
