### ISSUE TITLE
문제 추가!

### ISSUE THREAD

**Issue by ghost** [PMHStudio/DiscordCodeQuizBot#3]
(꼭, 이슈 하나당 하나의 문제만 적어주세요!)

## 문제의 언어
ex) Html

## 문제 (OX로 문제를 풀수있어야 합니다)
html에서 Enter를 칠려고 하면 `<br>`를 눌러야 한다.

## 답
O

## 풀이
Html에서는 키보드의 Enter를 눌러도 인식이 안 되고, 단지, 사용자가 보기 편할 수 있도록 하는 수단이기 떄문이다. 따라서, 글의 내용에서 Enter를 누를려고 하면 Enter 대신 `<br>`를 쳐야 한다

**Comment by pmh-only** [comment]
@seomingyu11 
문제 No.12으로 반영하였습니다.
