### ISSUE TITLE
문제 추가!

### ISSUE THREAD

**Issue by ghost** [PMHStudio/DiscordCodeQuizBot#4]
(꼭, 이슈 하나당 하나의 문제만 적어주세요!)

## 문제의 언어
ex) English

## 문제 (OX로 문제를 풀수있어야 합니다)
"English is fun!"이 알맞은 표현인지 고르시오

## 답
O

## 풀이
영어 책에 보면 English is fun이라고 되어 있지, English is not fun이라고 되어 있지 않는다.

**Comment by pmh-only** [comment]
@seomingyu11 
코드퀴즈에 맞지않는 언어입니다
