### ISSUE TITLE
awnser -> answer

### ISSUE THREAD

**Issue by comjun04** [PMHStudio/DiscordCodeQuizBot#9]
[QuizData.json](../blob/master/QuizData/QuizData.json) 파일에서
`answer`를 `awnser`로 작성하였습니다.

수정해 주시면 감사하겠습니다.

**Comment by pmh-only** [comment]
아하, 근데 귀찮은데

**Comment by ttakkku** [comment]
그거 저가 pr 날릴까요? @PMHStudio  @comjun04

**Comment by pmh-only** [comment]
그러면 감사하죠
